### ISSUE TITLE
Erros 

### ISSUE THREAD

**Issue by gautam1858** [ccd97/image-classify-server#1]
Hi I am getting these errors, when I upload the image it says loading and stops, the error in the command line is given below 

```
`Improper call to JPEG library in state 203
Internal Server Error: /classify_image/classify_api/
Traceback (most recent call last):
  File "/Users/neutrino/image-classify-server/tensorflow/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/neutrino/image-classify-server/tensorflow/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/neutrino/image-classify-server/tensorflow/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/neutrino/image-classify-server/tensorflow/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/neutrino/image-classify-server/classify_image/views.py", line 51, in classify_api
    classify_result = tf_classify(tmp_f, int(request.POST.get('k', MAX_K)))
  File "/Users/neutrino/image-classify-server/classify_image/views.py", line 72, in tf_classify
    predictions = SESS.run(GRAPH_TENSOR, {'DecodeJpeg/contents:0': image_data})
  File "/Users/neutrino/image-classify-server/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/Users/neutrino/image-classify-server/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/Users/neutrino/image-classify-server/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/Users/neutrino/image-classify-server/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
InvalidArgumentError: Invalid JPEG data, size 20480
	 [[Node: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_DecodeJpeg/contents_0)]]

Caused by op u'DecodeJpeg', defined at:
  File "/Users/neutrino/image-classify-server/tensorflow/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/Users/neutrino/image-classify-server/tensorflow/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/Users/neutrino/image-classify-server/tensorflow/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/neutrino/image-classify-server/tensorflow/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/neutrino/image-classify-server/tensorflow/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/neutrino/image-classify-server/tensorflow/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/Users/neutrino/image-classify-server/tensorflow/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/Users/neutrino/image-classify-server/tensorflow/lib/python2.7/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/Users/neutrino/image-classify-server/tensorflow/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/neutrino/image-classify-server/tensorflow/lib/python2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/neutrino/image-classify-server/tensorflow/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/neutrino/image-classify-server/tensorflow/lib/python2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/neutrino/image-classify-server/tf_inception/urls.py", line 17, in <module>
    from classify_image.views import classify, classify_api
  File "/Users/neutrino/image-classify-server/classify_image/views.py", line 31, in <module>
    SESS, GRAPH_TENSOR, LABELS = load_graph()
  File "/Users/neutrino/image-classify-server/classify_image/views.py", line 25, in load_graph
    _ = tf.import_graph_def(graph_def, name='')
  File "/Users/neutrino/image-classify-server/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 288, in import_graph_def
    op_def=op_def)
  File "/Users/neutrino/image-classify-server/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/neutrino/image-classify-server/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Invalid JPEG data, size 20480
	 [[Node: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_DecodeJpeg/contents_0)]]`
```

**Comment by ccd97** [comment]
Check **runtime.txt** file I have used `python-3.6.1`
So use python3 and not python2
